/**
 * Booking event webhooks (Sirvoy "Booking event webhook"): POST signed JSON
 * to URLs a manager registers when bookings are created, confirmed or
 * cancelled, or a payment is received. Receivers verify
 * X-Relief-Signature = "sha256=" + HMAC-SHA256(body, secret).
 *
 * Delivery never blocks or fails the booking flow; every attempt is logged
 * and failed ones can be resent from the Integrations page.
 */

import { isSafeFeedUrl } from "@/lib/channels/ical";
import { dataPath } from "@/lib/data-dir";
import { getSupabaseAdmin, isSupabaseEnabled } from "@/lib/db/client";
import type { ReservationRecord } from "@/lib/demo-store";
import { readJsonFile, updateJsonFile } from "@/lib/json-file-store";
import { roomDisplayName } from "@/lib/room-names";
import { readSettingsDoc, writeSettingsDoc } from "@/lib/settings-store";
import { createHmac, randomBytes, randomUUID } from "crypto";
import { z } from "zod";

export const WEBHOOK_EVENTS = ["booking.created", "booking.confirmed", "booking.cancelled", "payment.received"] as const;
export type WebhookEvent = (typeof WEBHOOK_EVENTS)[number];

export const webhookSchema = z.object({
  id: z.string().regex(/^[a-z0-9-]{1,60}$/),
  name: z.string().trim().min(1).max(60),
  url: z.string().trim().max(1000).refine(isSafeFeedUrl, { message: "Use a public https address" }),
  /** Generated by the server; never shown again after creation except to managers. */
  secret: z.string().min(16).max(128),
  events: z.array(z.enum(WEBHOOK_EVENTS)).min(1),
  active: z.boolean(),
});
export type Webhook = z.infer<typeof webhookSchema>;

export type Delivery = {
  id: string;
  webhookId: string;
  event: WebhookEvent;
  status: "sent" | "failed";
  httpStatus?: number;
  error?: string;
  at: string;
  body: string;
};

const KEY = "webhooks";
const LOG = dataPath("webhook-deliveries.json");
type LogStore = { deliveries: Delivery[] };

export async function getWebhooks(): Promise<Webhook[]> {
  const doc = await readSettingsDoc(KEY, (raw) => {
    const parsed = z.object({ hooks: z.array(webhookSchema) }).safeParse(raw);
    return parsed.success ? parsed.data : { hooks: [] };
  });
  return doc.hooks;
}

export const newWebhookSecret = () => `whsec_${randomBytes(24).toString("base64url")}`;

export async function saveWebhooks(input: unknown): Promise<Webhook[]> {
  const parsed = z.object({ hooks: z.array(webhookSchema).max(10) }).safeParse(input);
  if (!parsed.success) throw new Error(parsed.error.issues.map((i) => i.message).join("; "));
  return (await writeSettingsDoc(KEY, parsed.data)).hooks;
}

export function signBody(body: string, secret: string): string {
  return `sha256=${createHmac("sha256", secret).update(body).digest("hex")}`;
}

/** What receivers get: the booking without internal staff notes. */
export function bookingPayload(event: WebhookEvent, r: ReservationRecord, extra: Record<string, unknown> = {}) {
  return {
    event,
    occurredAt: new Date().toISOString(),
    booking: {
      id: r.id,
      groupId: r.groupId,
      status: r.status,
      channel: r.bookingChannel,
      room: { id: r.roomId, name: roomDisplayName(r.roomId), units: r.units ?? 1, numbers: r.assignedUnits ?? [] },
      checkIn: r.checkIn,
      checkOut: r.checkOut,
      nights: r.nights,
      guests: r.guests,
      guest: { firstName: r.firstName, lastName: r.lastName, email: r.email, phone: r.phone },
      totalNgn: r.quotedTotalNgn,
      depositNgn: r.quotedDepositNgn,
      couponCode: r.couponCode,
      createdAt: r.createdAt,
    },
    ...extra,
  };
}

async function logDelivery(delivery: Delivery): Promise<void> {
  if (!isSupabaseEnabled()) {
    await updateJsonFile(LOG, (): LogStore => ({ deliveries: [] }), (store) => {
      store.deliveries = [delivery, ...store.deliveries.filter((d) => d.id !== delivery.id)].slice(0, 300);
    });
    return;
  }
  await getSupabaseAdmin()?.from("webhook_deliveries").upsert({
    id: delivery.id,
    webhook_id: delivery.webhookId,
    event: delivery.event,
    status: delivery.status,
    http_status: delivery.httpStatus ?? null,
    error: delivery.error ?? null,
    at: delivery.at,
    body: delivery.body,
  });
}

export async function recentDeliveries(limit = 50): Promise<Delivery[]> {
  if (!isSupabaseEnabled()) {
    return (await readJsonFile(LOG, (): LogStore => ({ deliveries: [] }))).deliveries.slice(0, limit);
  }
  const { data } = (await getSupabaseAdmin()
    ?.from("webhook_deliveries")
    .select()
    .order("at", { ascending: false })
    .limit(limit)) ?? { data: [] };
  return (data ?? []).map((r) => ({
    id: r.id as string,
    webhookId: r.webhook_id as string,
    event: r.event as WebhookEvent,
    status: r.status as Delivery["status"],
    httpStatus: (r.http_status as number | null) ?? undefined,
    error: (r.error as string | null) ?? undefined,
    at: r.at as string,
    body: r.body as string,
  }));
}

async function deliver(hook: Webhook, event: WebhookEvent, body: string, deliveryId: string = randomUUID()): Promise<Delivery> {
  let result: Delivery;
  try {
    const res = await fetch(hook.url, {
      method: "POST",
      redirect: "error",
      signal: AbortSignal.timeout(5_000),
      headers: {
        "Content-Type": "application/json",
        "User-Agent": "ReliefHotels-Webhooks/1",
        "X-Relief-Event": event,
        "X-Relief-Delivery": deliveryId,
        "X-Relief-Signature": signBody(body, hook.secret),
      },
      body,
    });
    result = { id: deliveryId, webhookId: hook.id, event, status: res.ok ? "sent" : "failed", httpStatus: res.status, at: new Date().toISOString(), body };
  } catch (error) {
    result = { id: deliveryId, webhookId: hook.id, event, status: "failed", error: error instanceof Error ? error.message : "Request failed", at: new Date().toISOString(), body };
  }
  await logDelivery(result).catch(() => undefined);
  return result;
}

/** Send an event to every active webhook that wants it. Never throws. */
export async function emitBookingEvent(
  event: WebhookEvent,
  reservation: ReservationRecord,
  extra?: Record<string, unknown>,
): Promise<void> {
  try {
    const hooks = (await getWebhooks()).filter((h) => h.active && h.events.includes(event));
    if (hooks.length === 0) return;
    const body = JSON.stringify(bookingPayload(event, reservation, extra));
    await Promise.all(hooks.map((h) => deliver(h, event, body)));
  } catch (error) {
    console.warn("[webhooks] emit failed:", error);
  }
}

/** Deliver one event to one endpoint (the "Send test" button). */
export async function sendToWebhook(
  hook: Webhook,
  event: WebhookEvent,
  reservation: ReservationRecord,
  extra?: Record<string, unknown>,
): Promise<Delivery> {
  return deliver(hook, event, JSON.stringify(bookingPayload(event, reservation, extra)));
}

/** Resend a logged delivery with the same body (new signature with the current secret). */
export async function resendDelivery(deliveryId: string): Promise<Delivery | null> {
  const original = (await recentDeliveries(300)).find((d) => d.id === deliveryId);
  const hook = original && (await getWebhooks()).find((h) => h.id === original.webhookId);
  if (!original || !hook) return null;
  return deliver(hook, original.event, original.body, deliveryId);
}
